repos:
  # Clean notebooks
  - repo: https://github.com/srstevenson/nb-clean
    rev: 2.4.0
    hooks:
      - id: nb-clean
        stages: [pre-commit]
        args:
          - --remove-empty-cells
          - --preserve-cell-metadata
          - collapsed
          - scrolled
          - deletable
          - editable
          - format
          - name
          - tags
          - jupyter
          - execution
          - --
        exclude: ^(.*\/)*docs\/.*$

  # Various hooks from pre-commit
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-merge-conflict
        args: [--assume-in-merge]
      - id: detect-private-key
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        files: \.py$

  # Ruff: The fast Python linter and formatter (Replaces flake8 and black)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      # Linter
      - id: ruff
        args: [ --fix, --exit-non-zero-on-fix ]
        types_or: [ python, pyi ]
        exclude: ^notebooks/
      # Formatter
      - id: ruff-format
        types_or: [ python, pyi ]
        exclude: ^notebooks/
